name: Automated Testing Pipeline

on:
  push:
  pull_request:

jobs:
  backend-tests:
    name: Run Backend Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install Backend Dependencies
        working-directory: ./backend
        run: npm install

      - name: Run Backend Tests
        working-directory: ./backend
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          RESEND_API_KEY: ${{ secrets.RESEND_API_KEY }}
        run: npm test

  frontend-tests:
    name: Run Frontend Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install Frontend Dependencies
        working-directory: ./frontend
        run: npm install

      - name: Run Frontend Unit Tests
        working-directory: ./frontend
        env:
          VITE_MAPPEDIN_KEY: ${{ secrets.VITE_MAPPEDIN_KEY }}
          VITE_MAPPEDIN_SECRET: ${{ secrets.VITE_MAPPEDIN_SECRET }}
          VITE_GOOGLE_CLIENT_ID: ${{ secrets.VITE_GOOGLE_CLIENT_ID }}
          VITE_GOOGLE_CLIENT_SECRET: ${{ secrets.VITE_GOOGLE_CLIENT_SECRET }}
          VITE_GOOGLE_API_KEY: ${{ secrets.VITE_GOOGLE_API_KEY }}
          VITE_GOOGLE_MAPS_API_KEY: ${{ secrets.VITE_GOOGLE_API_KEY }}

        run: npm run test

  cypress-tests:
    name: Run Cypress Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install Frontend Dependencies
        working-directory: ./frontend
        run: npm install

      - name: Install Cypress Dependencies
        run: npm install

      - name: Install wait-on
        run: npm install -g wait-on

      - name: Install nodemon
        run: npm install -g nodemon

      - name: Install Backend Dependencies
        working-directory: ./backend
        run: npm install

      - name: Compile Backend Code
        working-directory: ./backend
        run: npm run build

      - name: Start Backend Server
        working-directory: ./backend
        run: nohup npm run dev > backend.log 2>&1 &
        env:
          NODE_ENV: test
          PORT: 3000
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          RESEND_API_KEY: ${{ secrets.RESEND_API_KEY }}

      - name: Wait for Backend Server
        run: wait-on http://localhost:3000/health

      - name: Start Frontend Server
        working-directory: ./frontend
        run: npm run dev &
        env:
          NODE_ENV: test
          VITE_MAPPEDIN_KEY: ${{ secrets.VITE_MAPPEDIN_KEY }}
          VITE_MAPPEDIN_SECRET: ${{ secrets.VITE_MAPPEDIN_SECRET }}
          VITE_GOOGLE_CLIENT_ID: ${{ secrets.VITE_GOOGLE_CLIENT_ID }}
          VITE_GOOGLE_CLIENT_SECRET: ${{ secrets.VITE_GOOGLE_CLIENT_SECRET }}
          VITE_GOOGLE_API_KEY: ${{ secrets.VITE_GOOGLE_API_KEY }}
          VITE_GOOGLE_MAPS_API_KEY: ${{ secrets.VITE_GOOGLE_API_KEY }}


      - name: Wait for Frontend Server
        run: wait-on http://localhost:5173

      - name: Run Cypress Tests
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          RESEND_API_KEY: ${{ secrets.RESEND_API_KEY }}
          VITE_MAPPEDIN_KEY: ${{ secrets.VITE_MAPPEDIN_KEY }}
          VITE_MAPPEDIN_SECRET: ${{ secrets.VITE_MAPPEDIN_SECRET }}
          VITE_GOOGLE_CLIENT_ID: ${{ secrets.VITE_GOOGLE_CLIENT_ID }}
          VITE_GOOGLE_CLIENT_SECRET: ${{ secrets.VITE_GOOGLE_CLIENT_SECRET }}
          VITE_GOOGLE_API_KEY: ${{ secrets.VITE_GOOGLE_API_KEY }}
          VITE_GOOGLE_MAPS_API_KEY: ${{ secrets.VITE_GOOGLE_API_KEY }}

        run: npx cypress run
